### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by AmberWilkie**
Adds short description of contents of this repository.

### CODE REVIEW

**Review by diraulo — CHANGES_REQUESTED** [review]
Why don't we add the link to the original exercise in the readme? 

Here's the link http://osherove.com/tdd-kata-1/

**Comment by AmberWilkie** [comment]
Yes, great idea. Will do that now.

**Review by diraulo — APPROVED** [review]
Looks good :shipit:

**Comment by diraulo** [comment]
Thanks @AmberWilkie for this

**Pull request merged**
